
apiVersion: v1
kind: Pod
metadata:
  name: manager
  namespace: cnflow
  labels:
    app: manager
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: master
  securityContext:
    runAsUser: 0
  containers:
    - name: manager
      image: cnflow/manager:latest
      imagePullPolicy: Never
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - NET_ADMIN
            - SYS_ADMIN
      command:
      - "/usr/local/bin/manager"
      args:
        - "--managerAddr=0.0.0.0"
        - "--managerPort=5317"
      ports:
        - name: grpc
          containerPort: 5317
      volumeMounts:
        - name: geoip-data
          mountPath: /data/geoip
          readOnly: true
    volumes:
      - name: geoip-data
        hostPath:
          path: /data/geoip
