// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: protobuf/ictc.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single network interface in a namespace.
type NetworkInterfaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Mtu           int32                  `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Ipv4Addresses []string               `protobuf:"bytes,5,rep,name=ipv4_addresses,json=ipv4Addresses,proto3" json:"ipv4_addresses,omitempty"`
	Ipv6Addresses string                 `protobuf:"bytes,6,opt,name=ipv6_addresses,json=ipv6Addresses,proto3" json:"ipv6_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterfaceInfo) Reset() {
	*x = NetworkInterfaceInfo{}
	mi := &file_protobuf_ictc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterfaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterfaceInfo) ProtoMessage() {}

func (x *NetworkInterfaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterfaceInfo.ProtoReflect.Descriptor instead.
func (*NetworkInterfaceInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkInterfaceInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *NetworkInterfaceInfo) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *NetworkInterfaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterfaceInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterfaceInfo) GetIpv4Addresses() []string {
	if x != nil {
		return x.Ipv4Addresses
	}
	return nil
}

func (x *NetworkInterfaceInfo) GetIpv6Addresses() string {
	if x != nil {
		return x.Ipv6Addresses
	}
	return ""
}

// Represents a network namespace and its interfaces.
type NetworkNamespaceInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inode         uint64                  `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Interfaces    []*NetworkInterfaceInfo `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkNamespaceInfo) Reset() {
	*x = NetworkNamespaceInfo{}
	mi := &file_protobuf_ictc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkNamespaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkNamespaceInfo) ProtoMessage() {}

func (x *NetworkNamespaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkNamespaceInfo.ProtoReflect.Descriptor instead.
func (*NetworkNamespaceInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkNamespaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkNamespaceInfo) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *NetworkNamespaceInfo) GetInterfaces() []*NetworkInterfaceInfo {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

// Security context information
type SecurityContextInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RunAsNonRoot             bool                   `protobuf:"varint,1,opt,name=run_as_non_root,json=runAsNonRoot,proto3" json:"run_as_non_root,omitempty"`
	RunAsUser                int64                  `protobuf:"varint,2,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	RunAsGroup               int64                  `protobuf:"varint,3,opt,name=run_as_group,json=runAsGroup,proto3" json:"run_as_group,omitempty"`
	FsGroup                  int64                  `protobuf:"varint,4,opt,name=fs_group,json=fsGroup,proto3" json:"fs_group,omitempty"`
	SeLinuxOptions           string                 `protobuf:"bytes,5,opt,name=se_linux_options,json=seLinuxOptions,proto3" json:"se_linux_options,omitempty"`
	Privileged               bool                   `protobuf:"varint,6,opt,name=privileged,proto3" json:"privileged,omitempty"`
	AllowPrivilegeEscalation bool                   `protobuf:"varint,7,opt,name=allow_privilege_escalation,json=allowPrivilegeEscalation,proto3" json:"allow_privilege_escalation,omitempty"`
	CapabilitiesAdd          []string               `protobuf:"bytes,8,rep,name=capabilities_add,json=capabilitiesAdd,proto3" json:"capabilities_add,omitempty"`
	CapabilitiesDrop         []string               `protobuf:"bytes,9,rep,name=capabilities_drop,json=capabilitiesDrop,proto3" json:"capabilities_drop,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SecurityContextInfo) Reset() {
	*x = SecurityContextInfo{}
	mi := &file_protobuf_ictc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityContextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityContextInfo) ProtoMessage() {}

func (x *SecurityContextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityContextInfo.ProtoReflect.Descriptor instead.
func (*SecurityContextInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityContextInfo) GetRunAsNonRoot() bool {
	if x != nil {
		return x.RunAsNonRoot
	}
	return false
}

func (x *SecurityContextInfo) GetRunAsUser() int64 {
	if x != nil {
		return x.RunAsUser
	}
	return 0
}

func (x *SecurityContextInfo) GetRunAsGroup() int64 {
	if x != nil {
		return x.RunAsGroup
	}
	return 0
}

func (x *SecurityContextInfo) GetFsGroup() int64 {
	if x != nil {
		return x.FsGroup
	}
	return 0
}

func (x *SecurityContextInfo) GetSeLinuxOptions() string {
	if x != nil {
		return x.SeLinuxOptions
	}
	return ""
}

func (x *SecurityContextInfo) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

func (x *SecurityContextInfo) GetAllowPrivilegeEscalation() bool {
	if x != nil {
		return x.AllowPrivilegeEscalation
	}
	return false
}

func (x *SecurityContextInfo) GetCapabilitiesAdd() []string {
	if x != nil {
		return x.CapabilitiesAdd
	}
	return nil
}

func (x *SecurityContextInfo) GetCapabilitiesDrop() []string {
	if x != nil {
		return x.CapabilitiesDrop
	}
	return nil
}

// Service account information
type ServiceAccountInfo struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Name                         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace                    string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AutomountServiceAccountToken bool                   `protobuf:"varint,3,opt,name=automount_service_account_token,json=automountServiceAccountToken,proto3" json:"automount_service_account_token,omitempty"`
	Secrets                      []string               `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty"`
	ImagePullSecrets             []string               `protobuf:"bytes,5,rep,name=image_pull_secrets,json=imagePullSecrets,proto3" json:"image_pull_secrets,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ServiceAccountInfo) Reset() {
	*x = ServiceAccountInfo{}
	mi := &file_protobuf_ictc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccountInfo) ProtoMessage() {}

func (x *ServiceAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccountInfo.ProtoReflect.Descriptor instead.
func (*ServiceAccountInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceAccountInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAccountInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceAccountInfo) GetAutomountServiceAccountToken() bool {
	if x != nil {
		return x.AutomountServiceAccountToken
	}
	return false
}

func (x *ServiceAccountInfo) GetSecrets() []string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ServiceAccountInfo) GetImagePullSecrets() []string {
	if x != nil {
		return x.ImagePullSecrets
	}
	return nil
}

// Geo location information
type GeoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Isp           string                 `protobuf:"bytes,7,opt,name=isp,proto3" json:"isp,omitempty"`
	Org           string                 `protobuf:"bytes,8,opt,name=org,proto3" json:"org,omitempty"`
	AsName        string                 `protobuf:"bytes,9,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	AsNumber      int32                  `protobuf:"varint,10,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoInfo) Reset() {
	*x = GeoInfo{}
	mi := &file_protobuf_ictc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoInfo) ProtoMessage() {}

func (x *GeoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoInfo.ProtoReflect.Descriptor instead.
func (*GeoInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{4}
}

func (x *GeoInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GeoInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GeoInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GeoInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoInfo) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *GeoInfo) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *GeoInfo) GetAsName() string {
	if x != nil {
		return x.AsName
	}
	return ""
}

func (x *GeoInfo) GetAsNumber() int32 {
	if x != nil {
		return x.AsNumber
	}
	return 0
}

// Pod metadata + network namespace info.
type PodInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase           string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	PodIp           string                 `protobuf:"bytes,4,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	PodUid          string                 `protobuf:"bytes,5,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Node            string                 `protobuf:"bytes,6,opt,name=node,proto3" json:"node,omitempty"`
	HostIp          string                 `protobuf:"bytes,7,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	HostNetwork     bool                   `protobuf:"varint,8,opt,name=host_network,json=hostNetwork,proto3" json:"host_network,omitempty"`
	NetnsInfo       *NetworkNamespaceInfo  `protobuf:"bytes,9,opt,name=netns_info,json=netnsInfo,proto3" json:"netns_info,omitempty"`
	ServiceAccount  *ServiceAccountInfo    `protobuf:"bytes,11,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	SecurityContext *SecurityContextInfo   `protobuf:"bytes,12,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	mi := &file_protobuf_ictc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{5}
}

func (x *PodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodInfo) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PodInfo) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *PodInfo) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PodInfo) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *PodInfo) GetHostNetwork() bool {
	if x != nil {
		return x.HostNetwork
	}
	return false
}

func (x *PodInfo) GetNetnsInfo() *NetworkNamespaceInfo {
	if x != nil {
		return x.NetnsInfo
	}
	return nil
}

func (x *PodInfo) GetServiceAccount() *ServiceAccountInfo {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *PodInfo) GetSecurityContext() *SecurityContextInfo {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

// Node metadata + network namespace info.
type NodeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid            string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	HostIp         string                 `protobuf:"bytes,4,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	KubeletVersion string                 `protobuf:"bytes,5,opt,name=kubelet_version,json=kubeletVersion,proto3" json:"kubelet_version,omitempty"`
	OsImage        string                 `protobuf:"bytes,6,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	Allocatable    map[string]string      `protobuf:"bytes,7,rep,name=allocatable,proto3" json:"allocatable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capacity       map[string]string      `protobuf:"bytes,8,rep,name=capacity,proto3" json:"capacity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NetnsInfo      *NetworkNamespaceInfo  `protobuf:"bytes,9,opt,name=netns_info,json=netnsInfo,proto3" json:"netns_info,omitempty"`
	GeoInfo        *GeoInfo               `protobuf:"bytes,11,opt,name=geo_info,json=geoInfo,proto3" json:"geo_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_protobuf_ictc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *NodeInfo) GetKubeletVersion() string {
	if x != nil {
		return x.KubeletVersion
	}
	return ""
}

func (x *NodeInfo) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *NodeInfo) GetAllocatable() map[string]string {
	if x != nil {
		return x.Allocatable
	}
	return nil
}

func (x *NodeInfo) GetCapacity() map[string]string {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *NodeInfo) GetNetnsInfo() *NetworkNamespaceInfo {
	if x != nil {
		return x.NetnsInfo
	}
	return nil
}

func (x *NodeInfo) GetGeoInfo() *GeoInfo {
	if x != nil {
		return x.GeoInfo
	}
	return nil
}

// Base network event information
type BaseNetworkEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP Header Fields
	SrcAddr    uint32 `protobuf:"varint,1,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	DstAddr    uint32 `protobuf:"varint,2,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	IpTos      uint32 `protobuf:"varint,3,opt,name=ip_tos,json=ipTos,proto3" json:"ip_tos,omitempty"`
	IpTotalLen uint32 `protobuf:"varint,4,opt,name=ip_total_len,json=ipTotalLen,proto3" json:"ip_total_len,omitempty"`
	IpId       uint32 `protobuf:"varint,5,opt,name=ip_id,json=ipId,proto3" json:"ip_id,omitempty"`
	IpFragOff  uint32 `protobuf:"varint,6,opt,name=ip_frag_off,json=ipFragOff,proto3" json:"ip_frag_off,omitempty"`
	IpTtl      uint32 `protobuf:"varint,7,opt,name=ip_ttl,json=ipTtl,proto3" json:"ip_ttl,omitempty"`
	IpProtocol uint32 `protobuf:"varint,8,opt,name=ip_protocol,json=ipProtocol,proto3" json:"ip_protocol,omitempty"`
	IpCheck    uint32 `protobuf:"varint,9,opt,name=ip_check,json=ipCheck,proto3" json:"ip_check,omitempty"`
	// Port Fields
	SrcPort uint32 `protobuf:"varint,11,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort uint32 `protobuf:"varint,12,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// TCP Header Fields
	Seq      uint32 `protobuf:"varint,21,opt,name=seq,proto3" json:"seq,omitempty"`
	AckSeq   uint32 `protobuf:"varint,22,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	TcpFlags uint32 `protobuf:"varint,23,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"`
	Window   uint32 `protobuf:"varint,24,opt,name=window,proto3" json:"window,omitempty"`
	TcpCheck uint32 `protobuf:"varint,25,opt,name=tcp_check,json=tcpCheck,proto3" json:"tcp_check,omitempty"`
	// UDP Header Fields
	UdpLen   uint32 `protobuf:"varint,31,opt,name=udp_len,json=udpLen,proto3" json:"udp_len,omitempty"`
	UdpCheck uint32 `protobuf:"varint,32,opt,name=udp_check,json=udpCheck,proto3" json:"udp_check,omitempty"`
	// Metadata
	TimestampNs   uint64 `protobuf:"varint,41,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	PayloadSize   uint32 `protobuf:"varint,42,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseNetworkEvent) Reset() {
	*x = BaseNetworkEvent{}
	mi := &file_protobuf_ictc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseNetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseNetworkEvent) ProtoMessage() {}

func (x *BaseNetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseNetworkEvent.ProtoReflect.Descriptor instead.
func (*BaseNetworkEvent) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{7}
}

func (x *BaseNetworkEvent) GetSrcAddr() uint32 {
	if x != nil {
		return x.SrcAddr
	}
	return 0
}

func (x *BaseNetworkEvent) GetDstAddr() uint32 {
	if x != nil {
		return x.DstAddr
	}
	return 0
}

func (x *BaseNetworkEvent) GetIpTos() uint32 {
	if x != nil {
		return x.IpTos
	}
	return 0
}

func (x *BaseNetworkEvent) GetIpTotalLen() uint32 {
	if x != nil {
		return x.IpTotalLen
	}
	return 0
}

func (x *BaseNetworkEvent) GetIpId() uint32 {
	if x != nil {
		return x.IpId
	}
	return 0
}

func (x *BaseNetworkEvent) GetIpFragOff() uint32 {
	if x != nil {
		return x.IpFragOff
	}
	return 0
}

func (x *BaseNetworkEvent) GetIpTtl() uint32 {
	if x != nil {
		return x.IpTtl
	}
	return 0
}

func (x *BaseNetworkEvent) GetIpProtocol() uint32 {
	if x != nil {
		return x.IpProtocol
	}
	return 0
}

func (x *BaseNetworkEvent) GetIpCheck() uint32 {
	if x != nil {
		return x.IpCheck
	}
	return 0
}

func (x *BaseNetworkEvent) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *BaseNetworkEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *BaseNetworkEvent) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *BaseNetworkEvent) GetAckSeq() uint32 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *BaseNetworkEvent) GetTcpFlags() uint32 {
	if x != nil {
		return x.TcpFlags
	}
	return 0
}

func (x *BaseNetworkEvent) GetWindow() uint32 {
	if x != nil {
		return x.Window
	}
	return 0
}

func (x *BaseNetworkEvent) GetTcpCheck() uint32 {
	if x != nil {
		return x.TcpCheck
	}
	return 0
}

func (x *BaseNetworkEvent) GetUdpLen() uint32 {
	if x != nil {
		return x.UdpLen
	}
	return 0
}

func (x *BaseNetworkEvent) GetUdpCheck() uint32 {
	if x != nil {
		return x.UdpCheck
	}
	return 0
}

func (x *BaseNetworkEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *BaseNetworkEvent) GetPayloadSize() uint32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

// HTTP event information
type HTTPEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseNetworkEvent      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	StatusCode    string                 `protobuf:"bytes,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	IsRequest     bool                   `protobuf:"varint,5,opt,name=is_request,json=isRequest,proto3" json:"is_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPEvent) Reset() {
	*x = HTTPEvent{}
	mi := &file_protobuf_ictc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPEvent) ProtoMessage() {}

func (x *HTTPEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPEvent.ProtoReflect.Descriptor instead.
func (*HTTPEvent) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{8}
}

func (x *HTTPEvent) GetBase() *BaseNetworkEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *HTTPEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPEvent) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *HTTPEvent) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *HTTPEvent) GetIsRequest() bool {
	if x != nil {
		return x.IsRequest
	}
	return false
}

// HTTP/2 event information
type HTTP2Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseNetworkEvent      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	FrameLength   uint32                 `protobuf:"varint,2,opt,name=frame_length,json=frameLength,proto3" json:"frame_length,omitempty"`
	FrameType     uint32                 `protobuf:"varint,3,opt,name=frame_type,json=frameType,proto3" json:"frame_type,omitempty"`
	FrameFlags    uint32                 `protobuf:"varint,4,opt,name=frame_flags,json=frameFlags,proto3" json:"frame_flags,omitempty"`
	StreamId      uint32                 `protobuf:"varint,5,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTP2Event) Reset() {
	*x = HTTP2Event{}
	mi := &file_protobuf_ictc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTP2Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTP2Event) ProtoMessage() {}

func (x *HTTP2Event) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTP2Event.ProtoReflect.Descriptor instead.
func (*HTTP2Event) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{9}
}

func (x *HTTP2Event) GetBase() *BaseNetworkEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *HTTP2Event) GetFrameLength() uint32 {
	if x != nil {
		return x.FrameLength
	}
	return 0
}

func (x *HTTP2Event) GetFrameType() uint32 {
	if x != nil {
		return x.FrameType
	}
	return 0
}

func (x *HTTP2Event) GetFrameFlags() uint32 {
	if x != nil {
		return x.FrameFlags
	}
	return 0
}

func (x *HTTP2Event) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *HTTP2Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// DNS event information
type DNSEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseNetworkEvent      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	TransactionId uint32                 `protobuf:"varint,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	QueryType     uint32                 `protobuf:"varint,3,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	QueryName     string                 `protobuf:"bytes,4,opt,name=query_name,json=queryName,proto3" json:"query_name,omitempty"`
	ResponseCode  uint32                 `protobuf:"varint,5,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	IsQuery       bool                   `protobuf:"varint,6,opt,name=is_query,json=isQuery,proto3" json:"is_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSEvent) Reset() {
	*x = DNSEvent{}
	mi := &file_protobuf_ictc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSEvent) ProtoMessage() {}

func (x *DNSEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSEvent.ProtoReflect.Descriptor instead.
func (*DNSEvent) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{10}
}

func (x *DNSEvent) GetBase() *BaseNetworkEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DNSEvent) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *DNSEvent) GetQueryType() uint32 {
	if x != nil {
		return x.QueryType
	}
	return 0
}

func (x *DNSEvent) GetQueryName() string {
	if x != nil {
		return x.QueryName
	}
	return ""
}

func (x *DNSEvent) GetResponseCode() uint32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *DNSEvent) GetIsQuery() bool {
	if x != nil {
		return x.IsQuery
	}
	return false
}

// Redis event information
type RedisEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseNetworkEvent      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CommandType   uint32                 `protobuf:"varint,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	RespType      uint32                 `protobuf:"varint,3,opt,name=resp_type,json=respType,proto3" json:"resp_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisEvent) Reset() {
	*x = RedisEvent{}
	mi := &file_protobuf_ictc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisEvent) ProtoMessage() {}

func (x *RedisEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisEvent.ProtoReflect.Descriptor instead.
func (*RedisEvent) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{11}
}

func (x *RedisEvent) GetBase() *BaseNetworkEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RedisEvent) GetCommandType() uint32 {
	if x != nil {
		return x.CommandType
	}
	return 0
}

func (x *RedisEvent) GetRespType() uint32 {
	if x != nil {
		return x.RespType
	}
	return 0
}

func (x *RedisEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ICMP event information
type ICMPEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseNetworkEvent      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Code          uint32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Id            uint32                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Sequence      uint32                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICMPEvent) Reset() {
	*x = ICMPEvent{}
	mi := &file_protobuf_ictc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICMPEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICMPEvent) ProtoMessage() {}

func (x *ICMPEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICMPEvent.ProtoReflect.Descriptor instead.
func (*ICMPEvent) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{12}
}

func (x *ICMPEvent) GetBase() *BaseNetworkEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ICMPEvent) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ICMPEvent) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ICMPEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ICMPEvent) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Kafka event information
type KafkaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseNetworkEvent      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ApiKey        uint32                 `protobuf:"varint,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiVersion    uint32                 `protobuf:"varint,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	CorrelationId uint32                 `protobuf:"varint,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KafkaEvent) Reset() {
	*x = KafkaEvent{}
	mi := &file_protobuf_ictc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaEvent) ProtoMessage() {}

func (x *KafkaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaEvent.ProtoReflect.Descriptor instead.
func (*KafkaEvent) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{13}
}

func (x *KafkaEvent) GetBase() *BaseNetworkEvent {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *KafkaEvent) GetApiKey() uint32 {
	if x != nil {
		return x.ApiKey
	}
	return 0
}

func (x *KafkaEvent) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *KafkaEvent) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *KafkaEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Acknowledgement from manager.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_protobuf_ictc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ictc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_protobuf_ictc_proto_rawDescGZIP(), []int{14}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protobuf_ictc_proto protoreflect.FileDescriptor

const file_protobuf_ictc_proto_rawDesc = "" +
	"\n" +
	"\x13protobuf/ictc.proto\x12\bprotobuf\"\xc1\x01\n" +
	"\x14NetworkInterfaceInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\x05R\x03mtu\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12%\n" +
	"\x0eipv4_addresses\x18\x05 \x03(\tR\ripv4Addresses\x12%\n" +
	"\x0eipv6_addresses\x18\x06 \x01(\tR\ripv6Addresses\"\x80\x01\n" +
	"\x14NetworkNamespaceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12>\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x1e.protobuf.NetworkInterfaceInfoR\n" +
	"interfaces\"\xf9\x02\n" +
	"\x13SecurityContextInfo\x12%\n" +
	"\x0frun_as_non_root\x18\x01 \x01(\bR\frunAsNonRoot\x12\x1e\n" +
	"\vrun_as_user\x18\x02 \x01(\x03R\trunAsUser\x12 \n" +
	"\frun_as_group\x18\x03 \x01(\x03R\n" +
	"runAsGroup\x12\x19\n" +
	"\bfs_group\x18\x04 \x01(\x03R\afsGroup\x12(\n" +
	"\x10se_linux_options\x18\x05 \x01(\tR\x0eseLinuxOptions\x12\x1e\n" +
	"\n" +
	"privileged\x18\x06 \x01(\bR\n" +
	"privileged\x12<\n" +
	"\x1aallow_privilege_escalation\x18\a \x01(\bR\x18allowPrivilegeEscalation\x12)\n" +
	"\x10capabilities_add\x18\b \x03(\tR\x0fcapabilitiesAdd\x12+\n" +
	"\x11capabilities_drop\x18\t \x03(\tR\x10capabilitiesDrop\"\xd5\x01\n" +
	"\x12ServiceAccountInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12E\n" +
	"\x1fautomount_service_account_token\x18\x03 \x01(\bR\x1cautomountServiceAccountToken\x12\x18\n" +
	"\asecrets\x18\x04 \x03(\tR\asecrets\x12,\n" +
	"\x12image_pull_secrets\x18\x05 \x03(\tR\x10imagePullSecrets\"\xff\x01\n" +
	"\aGeoInfo\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x10\n" +
	"\x03isp\x18\a \x01(\tR\x03isp\x12\x10\n" +
	"\x03org\x18\b \x01(\tR\x03org\x12\x17\n" +
	"\aas_name\x18\t \x01(\tR\x06asName\x12\x1b\n" +
	"\tas_number\x18\n" +
	" \x01(\x05R\basNumber\"\xa1\x03\n" +
	"\aPodInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x15\n" +
	"\x06pod_ip\x18\x04 \x01(\tR\x05podIp\x12\x17\n" +
	"\apod_uid\x18\x05 \x01(\tR\x06podUid\x12\x12\n" +
	"\x04node\x18\x06 \x01(\tR\x04node\x12\x17\n" +
	"\ahost_ip\x18\a \x01(\tR\x06hostIp\x12!\n" +
	"\fhost_network\x18\b \x01(\bR\vhostNetwork\x12=\n" +
	"\n" +
	"netns_info\x18\t \x01(\v2\x1e.protobuf.NetworkNamespaceInfoR\tnetnsInfo\x12E\n" +
	"\x0fservice_account\x18\v \x01(\v2\x1c.protobuf.ServiceAccountInfoR\x0eserviceAccount\x12H\n" +
	"\x10security_context\x18\f \x01(\v2\x1d.protobuf.SecurityContextInfoR\x0fsecurityContext\"\x94\x04\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\ahost_ip\x18\x04 \x01(\tR\x06hostIp\x12'\n" +
	"\x0fkubelet_version\x18\x05 \x01(\tR\x0ekubeletVersion\x12\x19\n" +
	"\bos_image\x18\x06 \x01(\tR\aosImage\x12E\n" +
	"\vallocatable\x18\a \x03(\v2#.protobuf.NodeInfo.AllocatableEntryR\vallocatable\x12<\n" +
	"\bcapacity\x18\b \x03(\v2 .protobuf.NodeInfo.CapacityEntryR\bcapacity\x12=\n" +
	"\n" +
	"netns_info\x18\t \x01(\v2\x1e.protobuf.NetworkNamespaceInfoR\tnetnsInfo\x12,\n" +
	"\bgeo_info\x18\v \x01(\v2\x11.protobuf.GeoInfoR\ageoInfo\x1a>\n" +
	"\x10AllocatableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rCapacityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x04\n" +
	"\x10BaseNetworkEvent\x12\x19\n" +
	"\bsrc_addr\x18\x01 \x01(\rR\asrcAddr\x12\x19\n" +
	"\bdst_addr\x18\x02 \x01(\rR\adstAddr\x12\x15\n" +
	"\x06ip_tos\x18\x03 \x01(\rR\x05ipTos\x12 \n" +
	"\fip_total_len\x18\x04 \x01(\rR\n" +
	"ipTotalLen\x12\x13\n" +
	"\x05ip_id\x18\x05 \x01(\rR\x04ipId\x12\x1e\n" +
	"\vip_frag_off\x18\x06 \x01(\rR\tipFragOff\x12\x15\n" +
	"\x06ip_ttl\x18\a \x01(\rR\x05ipTtl\x12\x1f\n" +
	"\vip_protocol\x18\b \x01(\rR\n" +
	"ipProtocol\x12\x19\n" +
	"\bip_check\x18\t \x01(\rR\aipCheck\x12\x19\n" +
	"\bsrc_port\x18\v \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\f \x01(\rR\adstPort\x12\x10\n" +
	"\x03seq\x18\x15 \x01(\rR\x03seq\x12\x17\n" +
	"\aack_seq\x18\x16 \x01(\rR\x06ackSeq\x12\x1b\n" +
	"\ttcp_flags\x18\x17 \x01(\rR\btcpFlags\x12\x16\n" +
	"\x06window\x18\x18 \x01(\rR\x06window\x12\x1b\n" +
	"\ttcp_check\x18\x19 \x01(\rR\btcpCheck\x12\x17\n" +
	"\audp_len\x18\x1f \x01(\rR\x06udpLen\x12\x1b\n" +
	"\tudp_check\x18  \x01(\rR\budpCheck\x12!\n" +
	"\ftimestamp_ns\x18) \x01(\x04R\vtimestampNs\x12!\n" +
	"\fpayload_size\x18* \x01(\rR\vpayloadSize\"\xa5\x01\n" +
	"\tHTTPEvent\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.protobuf.BaseNetworkEventR\x04base\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\tR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"is_request\x18\x05 \x01(\bR\tisRequest\"\xd6\x01\n" +
	"\n" +
	"HTTP2Event\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.protobuf.BaseNetworkEventR\x04base\x12!\n" +
	"\fframe_length\x18\x02 \x01(\rR\vframeLength\x12\x1d\n" +
	"\n" +
	"frame_type\x18\x03 \x01(\rR\tframeType\x12\x1f\n" +
	"\vframe_flags\x18\x04 \x01(\rR\n" +
	"frameFlags\x12\x1b\n" +
	"\tstream_id\x18\x05 \x01(\rR\bstreamId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\xdf\x01\n" +
	"\bDNSEvent\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.protobuf.BaseNetworkEventR\x04base\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\rR\rtransactionId\x12\x1d\n" +
	"\n" +
	"query_type\x18\x03 \x01(\rR\tqueryType\x12\x1d\n" +
	"\n" +
	"query_name\x18\x04 \x01(\tR\tqueryName\x12#\n" +
	"\rresponse_code\x18\x05 \x01(\rR\fresponseCode\x12\x19\n" +
	"\bis_query\x18\x06 \x01(\bR\aisQuery\"\x96\x01\n" +
	"\n" +
	"RedisEvent\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.protobuf.BaseNetworkEventR\x04base\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\rR\vcommandType\x12\x1b\n" +
	"\tresp_type\x18\x03 \x01(\rR\brespType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x8f\x01\n" +
	"\tICMPEvent\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.protobuf.BaseNetworkEventR\x04base\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\rR\x02id\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\rR\bsequence\"\xb7\x01\n" +
	"\n" +
	"KafkaEvent\x12.\n" +
	"\x04base\x18\x01 \x01(\v2\x1a.protobuf.BaseNetworkEventR\x04base\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\rR\x06apiKey\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\rR\n" +
	"apiVersion\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\rR\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa4\x03\n" +
	"\x04ictc\x12.\n" +
	"\bSyncPods\x12\x11.protobuf.PodInfo\x1a\r.protobuf.Ack(\x01\x120\n" +
	"\tSyncNodes\x12\x12.protobuf.NodeInfo\x1a\r.protobuf.Ack(\x01\x122\n" +
	"\n" +
	"HTTPEvents\x12\x13.protobuf.HTTPEvent\x1a\r.protobuf.Ack(\x01\x124\n" +
	"\vHTTP2Events\x12\x14.protobuf.HTTP2Event\x1a\r.protobuf.Ack(\x01\x120\n" +
	"\tDNSEvents\x12\x12.protobuf.DNSEvent\x1a\r.protobuf.Ack(\x01\x124\n" +
	"\vRedisEvents\x12\x14.protobuf.RedisEvent\x1a\r.protobuf.Ack(\x01\x122\n" +
	"\n" +
	"ICMPEvents\x12\x13.protobuf.ICMPEvent\x1a\r.protobuf.Ack(\x01\x124\n" +
	"\vKafkaEvents\x12\x14.protobuf.KafkaEvent\x1a\r.protobuf.Ack(\x01B\x11Z\x0fjitria/protobufb\x06proto3"

var (
	file_protobuf_ictc_proto_rawDescOnce sync.Once
	file_protobuf_ictc_proto_rawDescData []byte
)

func file_protobuf_ictc_proto_rawDescGZIP() []byte {
	file_protobuf_ictc_proto_rawDescOnce.Do(func() {
		file_protobuf_ictc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_ictc_proto_rawDesc), len(file_protobuf_ictc_proto_rawDesc)))
	})
	return file_protobuf_ictc_proto_rawDescData
}

var file_protobuf_ictc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protobuf_ictc_proto_goTypes = []any{
	(*NetworkInterfaceInfo)(nil), // 0: protobuf.NetworkInterfaceInfo
	(*NetworkNamespaceInfo)(nil), // 1: protobuf.NetworkNamespaceInfo
	(*SecurityContextInfo)(nil),  // 2: protobuf.SecurityContextInfo
	(*ServiceAccountInfo)(nil),   // 3: protobuf.ServiceAccountInfo
	(*GeoInfo)(nil),              // 4: protobuf.GeoInfo
	(*PodInfo)(nil),              // 5: protobuf.PodInfo
	(*NodeInfo)(nil),             // 6: protobuf.NodeInfo
	(*BaseNetworkEvent)(nil),     // 7: protobuf.BaseNetworkEvent
	(*HTTPEvent)(nil),            // 8: protobuf.HTTPEvent
	(*HTTP2Event)(nil),           // 9: protobuf.HTTP2Event
	(*DNSEvent)(nil),             // 10: protobuf.DNSEvent
	(*RedisEvent)(nil),           // 11: protobuf.RedisEvent
	(*ICMPEvent)(nil),            // 12: protobuf.ICMPEvent
	(*KafkaEvent)(nil),           // 13: protobuf.KafkaEvent
	(*Ack)(nil),                  // 14: protobuf.Ack
	nil,                          // 15: protobuf.NodeInfo.AllocatableEntry
	nil,                          // 16: protobuf.NodeInfo.CapacityEntry
}
var file_protobuf_ictc_proto_depIdxs = []int32{
	0,  // 0: protobuf.NetworkNamespaceInfo.interfaces:type_name -> protobuf.NetworkInterfaceInfo
	1,  // 1: protobuf.PodInfo.netns_info:type_name -> protobuf.NetworkNamespaceInfo
	3,  // 2: protobuf.PodInfo.service_account:type_name -> protobuf.ServiceAccountInfo
	2,  // 3: protobuf.PodInfo.security_context:type_name -> protobuf.SecurityContextInfo
	15, // 4: protobuf.NodeInfo.allocatable:type_name -> protobuf.NodeInfo.AllocatableEntry
	16, // 5: protobuf.NodeInfo.capacity:type_name -> protobuf.NodeInfo.CapacityEntry
	1,  // 6: protobuf.NodeInfo.netns_info:type_name -> protobuf.NetworkNamespaceInfo
	4,  // 7: protobuf.NodeInfo.geo_info:type_name -> protobuf.GeoInfo
	7,  // 8: protobuf.HTTPEvent.base:type_name -> protobuf.BaseNetworkEvent
	7,  // 9: protobuf.HTTP2Event.base:type_name -> protobuf.BaseNetworkEvent
	7,  // 10: protobuf.DNSEvent.base:type_name -> protobuf.BaseNetworkEvent
	7,  // 11: protobuf.RedisEvent.base:type_name -> protobuf.BaseNetworkEvent
	7,  // 12: protobuf.ICMPEvent.base:type_name -> protobuf.BaseNetworkEvent
	7,  // 13: protobuf.KafkaEvent.base:type_name -> protobuf.BaseNetworkEvent
	5,  // 14: protobuf.ictc.SyncPods:input_type -> protobuf.PodInfo
	6,  // 15: protobuf.ictc.SyncNodes:input_type -> protobuf.NodeInfo
	8,  // 16: protobuf.ictc.HTTPEvents:input_type -> protobuf.HTTPEvent
	9,  // 17: protobuf.ictc.HTTP2Events:input_type -> protobuf.HTTP2Event
	10, // 18: protobuf.ictc.DNSEvents:input_type -> protobuf.DNSEvent
	11, // 19: protobuf.ictc.RedisEvents:input_type -> protobuf.RedisEvent
	12, // 20: protobuf.ictc.ICMPEvents:input_type -> protobuf.ICMPEvent
	13, // 21: protobuf.ictc.KafkaEvents:input_type -> protobuf.KafkaEvent
	14, // 22: protobuf.ictc.SyncPods:output_type -> protobuf.Ack
	14, // 23: protobuf.ictc.SyncNodes:output_type -> protobuf.Ack
	14, // 24: protobuf.ictc.HTTPEvents:output_type -> protobuf.Ack
	14, // 25: protobuf.ictc.HTTP2Events:output_type -> protobuf.Ack
	14, // 26: protobuf.ictc.DNSEvents:output_type -> protobuf.Ack
	14, // 27: protobuf.ictc.RedisEvents:output_type -> protobuf.Ack
	14, // 28: protobuf.ictc.ICMPEvents:output_type -> protobuf.Ack
	14, // 29: protobuf.ictc.KafkaEvents:output_type -> protobuf.Ack
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protobuf_ictc_proto_init() }
func file_protobuf_ictc_proto_init() {
	if File_protobuf_ictc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_ictc_proto_rawDesc), len(file_protobuf_ictc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_ictc_proto_goTypes,
		DependencyIndexes: file_protobuf_ictc_proto_depIdxs,
		MessageInfos:      file_protobuf_ictc_proto_msgTypes,
	}.Build()
	File_protobuf_ictc_proto = out.File
	file_protobuf_ictc_proto_goTypes = nil
	file_protobuf_ictc_proto_depIdxs = nil
}
