// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: protobuf/ictc.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ictc_SyncPods_FullMethodName    = "/protobuf.ictc/SyncPods"
	Ictc_SyncNodes_FullMethodName   = "/protobuf.ictc/SyncNodes"
	Ictc_HTTPEvents_FullMethodName  = "/protobuf.ictc/HTTPEvents"
	Ictc_HTTP2Events_FullMethodName = "/protobuf.ictc/HTTP2Events"
	Ictc_DNSEvents_FullMethodName   = "/protobuf.ictc/DNSEvents"
	Ictc_RedisEvents_FullMethodName = "/protobuf.ictc/RedisEvents"
	Ictc_ICMPEvents_FullMethodName  = "/protobuf.ictc/ICMPEvents"
	Ictc_KafkaEvents_FullMethodName = "/protobuf.ictc/KafkaEvents"
)

// IctcClient is the client API for Ictc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IctcClient interface {
	// Agents stream PodInfo messages to the manager.
	SyncPods(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PodInfo, Ack], error)
	// Agents stream NodeInfo messages to the manager.
	SyncNodes(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NodeInfo, Ack], error)
	// Network events streaming
	HTTPEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HTTPEvent, Ack], error)
	HTTP2Events(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HTTP2Event, Ack], error)
	DNSEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DNSEvent, Ack], error)
	RedisEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RedisEvent, Ack], error)
	ICMPEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ICMPEvent, Ack], error)
	KafkaEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[KafkaEvent, Ack], error)
}

type ictcClient struct {
	cc grpc.ClientConnInterface
}

func NewIctcClient(cc grpc.ClientConnInterface) IctcClient {
	return &ictcClient{cc}
}

func (c *ictcClient) SyncPods(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PodInfo, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ictc_ServiceDesc.Streams[0], Ictc_SyncPods_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PodInfo, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_SyncPodsClient = grpc.ClientStreamingClient[PodInfo, Ack]

func (c *ictcClient) SyncNodes(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NodeInfo, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ictc_ServiceDesc.Streams[1], Ictc_SyncNodes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeInfo, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_SyncNodesClient = grpc.ClientStreamingClient[NodeInfo, Ack]

func (c *ictcClient) HTTPEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HTTPEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ictc_ServiceDesc.Streams[2], Ictc_HTTPEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HTTPEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_HTTPEventsClient = grpc.ClientStreamingClient[HTTPEvent, Ack]

func (c *ictcClient) HTTP2Events(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HTTP2Event, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ictc_ServiceDesc.Streams[3], Ictc_HTTP2Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HTTP2Event, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_HTTP2EventsClient = grpc.ClientStreamingClient[HTTP2Event, Ack]

func (c *ictcClient) DNSEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DNSEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ictc_ServiceDesc.Streams[4], Ictc_DNSEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DNSEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_DNSEventsClient = grpc.ClientStreamingClient[DNSEvent, Ack]

func (c *ictcClient) RedisEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RedisEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ictc_ServiceDesc.Streams[5], Ictc_RedisEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RedisEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_RedisEventsClient = grpc.ClientStreamingClient[RedisEvent, Ack]

func (c *ictcClient) ICMPEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ICMPEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ictc_ServiceDesc.Streams[6], Ictc_ICMPEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ICMPEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_ICMPEventsClient = grpc.ClientStreamingClient[ICMPEvent, Ack]

func (c *ictcClient) KafkaEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[KafkaEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ictc_ServiceDesc.Streams[7], Ictc_KafkaEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KafkaEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_KafkaEventsClient = grpc.ClientStreamingClient[KafkaEvent, Ack]

// IctcServer is the server API for Ictc service.
// All implementations should embed UnimplementedIctcServer
// for forward compatibility.
type IctcServer interface {
	// Agents stream PodInfo messages to the manager.
	SyncPods(grpc.ClientStreamingServer[PodInfo, Ack]) error
	// Agents stream NodeInfo messages to the manager.
	SyncNodes(grpc.ClientStreamingServer[NodeInfo, Ack]) error
	// Network events streaming
	HTTPEvents(grpc.ClientStreamingServer[HTTPEvent, Ack]) error
	HTTP2Events(grpc.ClientStreamingServer[HTTP2Event, Ack]) error
	DNSEvents(grpc.ClientStreamingServer[DNSEvent, Ack]) error
	RedisEvents(grpc.ClientStreamingServer[RedisEvent, Ack]) error
	ICMPEvents(grpc.ClientStreamingServer[ICMPEvent, Ack]) error
	KafkaEvents(grpc.ClientStreamingServer[KafkaEvent, Ack]) error
}

// UnimplementedIctcServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIctcServer struct{}

func (UnimplementedIctcServer) SyncPods(grpc.ClientStreamingServer[PodInfo, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method SyncPods not implemented")
}
func (UnimplementedIctcServer) SyncNodes(grpc.ClientStreamingServer[NodeInfo, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method SyncNodes not implemented")
}
func (UnimplementedIctcServer) HTTPEvents(grpc.ClientStreamingServer[HTTPEvent, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method HTTPEvents not implemented")
}
func (UnimplementedIctcServer) HTTP2Events(grpc.ClientStreamingServer[HTTP2Event, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method HTTP2Events not implemented")
}
func (UnimplementedIctcServer) DNSEvents(grpc.ClientStreamingServer[DNSEvent, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method DNSEvents not implemented")
}
func (UnimplementedIctcServer) RedisEvents(grpc.ClientStreamingServer[RedisEvent, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method RedisEvents not implemented")
}
func (UnimplementedIctcServer) ICMPEvents(grpc.ClientStreamingServer[ICMPEvent, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method ICMPEvents not implemented")
}
func (UnimplementedIctcServer) KafkaEvents(grpc.ClientStreamingServer[KafkaEvent, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method KafkaEvents not implemented")
}
func (UnimplementedIctcServer) testEmbeddedByValue() {}

// UnsafeIctcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IctcServer will
// result in compilation errors.
type UnsafeIctcServer interface {
	mustEmbedUnimplementedIctcServer()
}

func RegisterIctcServer(s grpc.ServiceRegistrar, srv IctcServer) {
	// If the following call pancis, it indicates UnimplementedIctcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ictc_ServiceDesc, srv)
}

func _Ictc_SyncPods_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IctcServer).SyncPods(&grpc.GenericServerStream[PodInfo, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_SyncPodsServer = grpc.ClientStreamingServer[PodInfo, Ack]

func _Ictc_SyncNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IctcServer).SyncNodes(&grpc.GenericServerStream[NodeInfo, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_SyncNodesServer = grpc.ClientStreamingServer[NodeInfo, Ack]

func _Ictc_HTTPEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IctcServer).HTTPEvents(&grpc.GenericServerStream[HTTPEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_HTTPEventsServer = grpc.ClientStreamingServer[HTTPEvent, Ack]

func _Ictc_HTTP2Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IctcServer).HTTP2Events(&grpc.GenericServerStream[HTTP2Event, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_HTTP2EventsServer = grpc.ClientStreamingServer[HTTP2Event, Ack]

func _Ictc_DNSEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IctcServer).DNSEvents(&grpc.GenericServerStream[DNSEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_DNSEventsServer = grpc.ClientStreamingServer[DNSEvent, Ack]

func _Ictc_RedisEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IctcServer).RedisEvents(&grpc.GenericServerStream[RedisEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_RedisEventsServer = grpc.ClientStreamingServer[RedisEvent, Ack]

func _Ictc_ICMPEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IctcServer).ICMPEvents(&grpc.GenericServerStream[ICMPEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_ICMPEventsServer = grpc.ClientStreamingServer[ICMPEvent, Ack]

func _Ictc_KafkaEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IctcServer).KafkaEvents(&grpc.GenericServerStream[KafkaEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ictc_KafkaEventsServer = grpc.ClientStreamingServer[KafkaEvent, Ack]

// Ictc_ServiceDesc is the grpc.ServiceDesc for Ictc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ictc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ictc",
	HandlerType: (*IctcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncPods",
			Handler:       _Ictc_SyncPods_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncNodes",
			Handler:       _Ictc_SyncNodes_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "HTTPEvents",
			Handler:       _Ictc_HTTPEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "HTTP2Events",
			Handler:       _Ictc_HTTP2Events_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DNSEvents",
			Handler:       _Ictc_DNSEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RedisEvents",
			Handler:       _Ictc_RedisEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ICMPEvents",
			Handler:       _Ictc_ICMPEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "KafkaEvents",
			Handler:       _Ictc_KafkaEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/ictc.proto",
}
